### ISSUE TITLE
apache

### ISSUE THREAD

**Issue by 3300780** [julibinho/2dSS#1]
Bonjour,

Quand vous parlez d'apache, c'est bien le serveur que l'on doit installer pour voir localement si nos pages html, nos script php, fonctionnent correctement ?

Cordialement,

Charlotte.

**Comment by julibinho** [comment]
oui, c'est bien ça, si c'est linux peut-etre il est deja installer, verifiez.

à plus

**Comment by 3300780** [comment]
J'avais bien les paquets j'ai fait tout les install et autres lignes de commande charger mes pages html fonctionne seulement quand je veux charger une page html avec un script php, ce script n'est pas interpreté. J'ai passé pas mal de temps sur internet mais je ne sais plus quoi faire. A un moment ils disent qu'il faut que dans mon fichier de config d'apache2 je doit avoir un lien avec php5 seulement j'ai aucunes idees de comment faire. Pourriez vous m'aidez ?

**Comment by julibinho** [comment]
Salut,

Vous pouvez l'installer comme un module de apache, voir le debut de ce video https://www.grafikart.fr/formations/serveur-linux/php-module-apache, le probleme de ça c'est la performance, mais localement ça doit aller, dans le server php sera installer comme il faut.

Dites moi si ça vous aide.
à+

**Comment by julibinho** [comment]
Bonjour,

Je pense que votre probleme c'est simpliment configuration.
Est-ce que vous avez enlevé les # de module dans le fichier httpd.conf?

LoadModule authn_core_module libexec/apache2/mod_authn_core.so
LoadModule authz_core_module libexec/apache2/mod_authz_core.so
LoadModule authz_host_module libexec/apache2/mod_authz_host.so
LoadModule userdir_module libexec/apache2/mod_userdir.so
LoadModule include_module libexec/apache2/mod_include.so
LoadModule rewrite_module libexec/apache2/mod_rewrite.so

LoadModule php5_module libexec/apache2/libphp5.so
Include /private/etc/apache2/extra/httpd-userdir.conf

Il faut aussi chercher dans le fichier la hashtag
<Directory "**/Users/julianab/sites**">
   #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   AllowOverride FileInfo AuthConfig Limit
    # 
    AllowOverride All
</Directory>

Faites attention, je vous donné ces commands comme exemple, ma machine est MacOS alors les path peut etre diferents, aussi apres Directory mettre votre work directory.

**Ne oubliez pas de stop et restart le service apache apres les modifis.** 
Bon courage,
  Dites moi si vous avez reussit,
à+

**Comment by 3300780** [comment]
Bonjour,

En fait je mettais mes fichiers dans un mauvais repertoire.
Maintenant que je les mets dans /var/www/html cela fonctionne c'est la video qui m'y a fait penser !
Merci beaucoup de votre aide.
