### ISSUE TITLE
Projet

### ISSUE THREAD

**Issue by 3300780** [julibinho/2dSS#2]
Bonjour,
Avec Priya nous nous sommes rendu compte que nous n'avions pas très bien compris lorsque vous nous avez parlé de pipeline pour la deuxieme phase du projet. Pourriez vous nous réexpliquer?
Cordialement,
Cochard Charlotte.

**Comment by julibinho** [comment]
Dans la première phase nous allons pas exécuter les outils d’alignement de séquence et de prédiction de structure secondaire, c'est l'utilisateur que doit nous fournir ces donnes pour pouvoir utilise le site web et regarder l'alignement 2D. Dans la deuxième phase l'utilisateur va nous fournir seulement les séquences et nous allons les alignes, prédire leur structure secondaire en utilisant les outils disponibles et lui montre l'alignement 2D, j'appelle ça pipeline, car nous allons combiner les trois outils (alignement + Prediction de structure + production du alignement 2D) et faciliter la tache du utilisateur, c'est claire?

à+ et bon courage
