### ISSUE TITLE
View 2d Alignment

### ISSUE THREAD

**Issue by julibinho** [julibinho/2dSS#3]
Bonjour,

La prochaine etaphe sera implementer le Menu "View 2d Alignment", vous pouvez venir la semaine prochaine pour en discuter?
Je suis libre lundi ou mardi matin.

Cordialement,
  Juliana

**Comment by 3300780** [comment]
Bonjour Madame,
Je suis libre lundi matin.
Cordialement,
Charlotte.

**Comment by julibinho** [comment]
ok, Priya, ça vous va lundi 10hs?

**Comment by 3408247** [comment]
Bonjour,

Oui c'est bon pour lundi matin pour moi aussi.

 Cdt
Priya

**Comment by julibinho** [comment]
ok, c'est noté à lundi.
