### ISSUE TITLE
php

### ISSUE THREAD

**Issue by 3300780** [julibinho/2dSS#4]
Bonjour madame,
voila j'essaye d'exécuter le script 2dsstoaln.py dans php j'ai essayé avec exec ou system mais je n'arrive pas a comprendre comment cela fonctionne parceque même avec un script censé ecrire seulement bonjour cela ne fonctionne pas.
Je n'arrive pas à recuperer le fichier normalement creer pour notre script car je pense que ce que j'utilise ne fonctionne pas.
Pourriez vous m'éclairer?
Cordialement,
Charlotte.

**Comment by julibinho** [comment]
salut,

quelle est l'error dans le log du apache?
C'est peut etre permission pour ecrire un fichier.

à+

**Comment by julibinho** [comment]
Salut,
chez moi ça marche comme ça

j'ai creer un dossier dir et j'ai donner la permission 777
mkdir dir
chmod 777 dir

j'ai un script t.sh
echo "hi" > /Users/julianab/sites/dir/a.txt 

dans mon php de teste j'ai ecrit
 <html>
 <head>
  <title>Test PHP</title>
 </head>
 <body>
<?php
// depuis PHP 5
exec('/Users/julianab/sites/t.sh');
//print $out
$file = '/Users/julianab/sites/dir/a.txt';
readfile($file);
?>
 </body>
</html>

**Comment by julibinho** [comment]
dans mon php de teste j'ai ecrit
 <html>
 <head>
  <title>Test PHP</title>
 </head>
 <body>
<?php
// depuis PHP 5
exec('/Users/julianab/sites/t.sh');
//print $out
$file = '/Users/julianab/sites/dir/a.txt';
readfile($file);
?>
 </body>
</html>

**Comment by julibinho** [comment]
Github est en train d'interpreter mon php, j'ai enleve le tag ?
<php
// depuis PHP 5
exec('/Users/julianab/sites/t.sh');
//print $out
$file = '/Users/julianab/sites/dir/a.txt';
readfile($file);
>
