### ISSUE TITLE
Prochaine rencontre

### ISSUE THREAD

**Issue by 3408247** [julibinho/2dSS#5]
Bonjour Madame,

Etant donné que nous avons des partiels la semaine prochaine, est-ce possible de décaler notre prochaine rencontre pour jeudi le 2 mars ?

Cordialement,

Priya

**Comment by julibinho** [comment]
Bonjour,

ok, à 10hs aussi?

à+

**Comment by 3408247** [comment]
Oui, 10hr c'est ok pour moi.

**Comment by 3300780** [comment]
Ok pour moi aussi.
