### ISSUE TITLE
Download result

### ISSUE THREAD

**Issue by 3300780** [julibinho/2dSS#7]
Bonjour madame,

Comme je n'arrive pas a convertir un svg en format png j'ai juste donné au fichier une extention de type png et en ouvrant dans un logiciel de traitement de texte cela fonctionne. Cela vous suffis t il ?
De plus je n'arrive pas a le convertir en format pdf j'ai essaye avec la librairie fpdf mais il me faudrait plus de temps car j'ai beaucoup de difficultés.

Cordialement,

Cochard Charlotte.

**Comment by julibinho** [comment]
ok, pas de problem.
