### ISSUE TITLE
Anulation rendez-vous

### ISSUE THREAD

**Issue by julibinho** [julibinho/2dSS#8]
Bonjour,

Malheureusement, je ne peux pas vous voir demain comme prevú. 
Vous pouvez lundi 13/03 à 10hs?

à+

**Comment by 3300780** [comment]
Bonjour madame,

Il n'y a aucuns soucis. C'est ok pour moi.
Cordialement,

Charlotte.

**Comment by 3408247** [comment]
Bonjour,

Pour moi aussi ok.

Cordialement 

Priya
