### ISSUE TITLE
Format .2dpred

### ISSUE THREAD

**Issue by 3408247** [julibinho/2dSS#9]
Bonjour Madame,

Pour le fichier data .2dpred, les deux colonnes doivent-elles aussi être séparées par des espaces comme pour le fichier .aln (et donc doivent aussi être de taille 14 maximum ) ? Parce que quand je copie colle le pred dans la deuxième texte box, c'est comme ci la col1 et la col2 ne sont pas séparées par des espaces. Cela pose quelques difficultés pour bien tester le formattage.

Merci d'avance

**Comment by julibinho** [comment]
Je suis en train de voir.

à+
